import type { Metadata } from 'next';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
Honor is a curated toolkit designed to honor the best in modern web development. It brings together powerful tools, essential packages, and reliable dependencies to help developers build fast, scalable, and beautifully crafted web applications with ease.